### ISSUE TITLE
Cannot install individual package in individual yarn workspace

### ISSUE THREAD

**Issue by kylemh** [charlie-tango/hooks#92]
Tried using `yarn workspace @myorg/workspace_packagename add @charlietango/use-native-lazy-loading` to no avail.

As a workaround, I just installed all the hooks to the workspace with `yarn add @charlietango/hooks -W`

![Screen Shot 2020-05-04 at 4 11 07 PM](https://user-images.githubusercontent.com/9523719/81022411-60a9e280-8e22-11ea-8ed7-590dfb5b41c2.png)

Relevant aspect of `yarn-error.log`

```
Arguments: 
  /Users/kyleholmberg/.nvm/versions/node/v10.19.0/bin/node /Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js add @charlietango/use-native-lazy-loading

PATH: 
  /usr/local/opt/postgresql@9.6/bin:/Users/kyleholmberg/.nvm/versions/node/v10.19.0/bin:/Users/kyleholmberg/.rbenv/plugins/ruby-build/bin:/Users/kyleholmberg/.rbenv/shims:/Users/kyleholmberg/.rbenv/bin:/usr/local/sbin:/Users/kyleholmberg/.nvm/versions/node/v10.20.1/bin:/usr/local/mysql/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Postgres.app/Contents/Versions/9.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kyleholmberg/.rbenv/plugins/ruby-build/bin:/Users/kyleholmberg/.rbenv/shims:/Users/kyleholmberg/.rbenv/bin:/usr/local/sbin:/Users/kyleholmberg/.nvm/versions/node/v10.16.3/bin:/usr/local/mysql/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Postgres.app/Contents/Versions/9.5/bin:/Users/kyleholmberg/gocode/bin:/usr/local/opt/postgresql/bin:/Users/kyleholmberg/gocode/bin

Yarn version: 
  1.22.4

Node version: 
  10.19.0

Platform: 
  darwin x64

Trace: 
  Invariant Violation: expected workspace package to exist for "jest-config"
      at invariant (/Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js:2314:15)
      at _loop2 (/Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js:94976:9)
      at PackageHoister.init (/Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js:95035:19)
      at PackageLinker.getFlatHoistedTree (/Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js:48743:20)
      at PackageLinker.<anonymous> (/Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js:48754:27)
      at Generator.next (<anonymous>)
      at step (/Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js:310:30)
      at /Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js:328:14
      at new Promise (<anonymous>)
      at new F (/Users/kyleholmberg/.nvm/versions/node/v10.19.0/lib/node_modules/yarn/lib/cli.js:5301:28)

npm manifest: 
  {
    "name": "@innocuous/components",
    "version": "2.1.1",
    "description": "A set of harmless React components.",
    "license": "MIT",
    "keywords": [
      "javascript",
      "typescript",
      "react"
    ],
    "main": "dist/index.js",
    "umd:main": "dist/components.umd.production.js",
    "module": "dist/components.es.production.js",
    "typings": "dist/index.d.ts",
    "files": [
      "dist"
    ],
    "scripts": {
      "build": "tsdx build",
      "lint": "tsdx lint",
      "start": "tsdx watch",
      "test": "tsdx test --env=jsdom"
    },
    "peerDependencies": {
      "react": ">=16.8.6",
      "react-dom": ">=16.8.6"
    },
    "dependencies": {
      "@innocuous/hooks": "^2.1.1"
    },
    "repository": {
      "type": "git",
      "url": "https://github.com/innocuous-tech/core.git",
      "directory": "packages/components"
    },
    "homepage": "https://github.com/innocuous-tech/core/tree/master/packages/components"
  }

```

**Comment by thebuilder** [comment]
Sounds weird 🤔

**Comment by VahanSargsyan** [comment]
same issue
